In [1]:
import numpy as np


In [2]:

list1 = [1,2,3,4,5]
list1


[1, 2, 3, 4, 5]

In [3]:

arr = np.array(list1)
arr

array([1, 2, 3, 4, 5])

In [4]:
arr1 = np.array([5,6,7,8,9,10])
arr1

array([ 5,  6,  7,  8,  9, 10])

In [7]:
# 2차원 배열 생성하기
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# 배열의 크기를 확인하는 방법 > .shape
# 출력의 형태 (행, 열)
print(arr1)
print(arr1.shape)

[ 5  6  7  8  9 10]
(6,)


In [9]:
print(arr2)
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [10]:
# 배열의 전체 요소 개수를 확인하는 방법 >> .size
print(arr1.size)
print(arr2.size)

6
6


In [11]:
arr

array([1, 2, 3, 4, 5])

In [14]:
list1=[1,'a',2.3]
list1

[1, 'a', 2.3]

In [15]:
arr = np.array(list1)
arr

array(['1', 'a', '2.3'], dtype='<U32')

In [16]:
# 배열의 데이터 타입을 확인할 수 있는 속성 >>> .dtype
arr.dtype

dtype('<U32')

In [17]:
# 배열의 차원을 확인할 수 있는 속성 >>. .ndim
print(arr.ndim)
print(arr2.ndim)

1
2


In [25]:
# 특정값으로 배열 생성하기
# 0으로 이뤄진 배열 생성>> .zeros((행,열))
arr_zero = np.zeros((2,2), dtype='int')
arr_zero

array([[0, 0],
       [0, 0]])

In [28]:
arr_one = np.ones((4,4), dtype = 'int')
arr_one

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [29]:
# 내가 원하는 데이터로 배열 생성하기 >> full((행,열), 데이터 값)
arr_full = np.full((5,5), 7)
arr_full

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [38]:
# 1~50 숫ㅅ자를 1차원 배열에 저장하기 !

list1 = []

for i in range(1, 51):
    # 리스트에 값 추가하기 >> append():
    list1.append(i)
    
print(list1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


In [39]:
arr = np.array(list1)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [40]:
# arrange() >> range의 기능과 array의 기능이 
arr2 = np.arange(1,40,3)
arr2

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37])

In [41]:
# numpy를 활용하여 랜덤수 생성하기]
# rand(행, 열)

arr3 = np.random.rand(2,3)
arr3


array([[0.00971276, 0.3404339 , 0.09988336],
       [0.28947832, 0.73519399, 0.51709732]])

In [49]:
# 정수형의 데이터로 랜덤 배열 만들기 >> randint ( 시작수 , 끝수 , seize = (헹, 열))
arr4 = np.random.randint(1, 11, size=(3,4))
arr4

array([[ 1,  9,  9,  8],
       [10,  6,  8,  7],
       [ 1,  9,  4,  9]])

In [50]:
arr1

array([ 5,  6,  7,  8,  9, 10])

In [51]:
arr1 * 2

array([10, 12, 14, 16, 18, 20])

In [52]:
arr1 + 2

array([ 7,  8,  9, 10, 11, 12])

In [53]:
# loadtxt(파일명.확장자, delimiter = '기준')
data = np.loadtxt('height_weight.txt', delimiter = ',')

In [54]:
data

array([[175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
        179. ],
       [ 65.6,  88. ,  79.2,  69.3,  55. ,  71.2,  73. ,  68.9,  74. ,
         82. ]])

In [62]:
#키에 대한 데이터
height = data[0]
weight = data[1]

In [63]:
# 각 키에 대한 데이터 변경이 필요하다
# cm > m / 1cm >> 0.01m

print(height)

[175.2 180.3 175.  169.2 185.2 188.  177.6 178.2 177.  179. ]


In [64]:
height = height *0.01

In [65]:
weight / (height * height)

array([21.37153104, 27.07018468, 25.86122449, 24.20652885, 16.03543423,
       20.14486193, 23.14392095, 21.69720651, 23.62028791, 25.59220998])

In [66]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [67]:
print(arr1)

[ 5  6  7  8  9 10]


In [68]:
print(arr2)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37]


In [69]:
print(list1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


In [74]:
print(arr4)

[[ 1  9  9  8]
 [10  6  8  7]
 [ 1  9  4  9]]


In [75]:
# 배열의 인덱싱 >> 원하는 행과 열을 선택하여 특정 값만 추출해 올 수 있다.
arr4[2][1]

9

In [76]:
arr4[2,1]

9

In [81]:
arr1 = np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
arr1[2 : 7]

array([3, 4, 5, 6, 7])

In [87]:
list1 = [1,2,3,4,5]
list1[1:4] = [2]
list1

[1, 2, 5]

In [88]:
# reshpae를 사용할 때에는 행과 열의 크기가 실제 데이터의 수와 일치하도록 설계!
# 데이터의 갯수 = 행 * 열
arr2 = np.arange(50).reshape(5, 10)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [89]:
arr2[2][8]

28

In [90]:
# arr[행(시작:끝), 열(시작:끝)]

arr2[0:2, 0:5]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [92]:
arr2[ :, :1]

array([[ 0],
       [10],
       [20],
       [30],
       [40]])

In [95]:
arr2[2,1]

21

In [103]:
# 다른위치의 데이터 가져오기 [행[행1,행2],[열1,열2]]
arr2[[2,3], [2,3]]

array([22, 33])

In [104]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
#sum() >>> 데이터의 모든 요소들을 합산 하는 함수
arr1.sum()

55

In [106]:
# mean()>  데이터에 대하여 평균값을 계산하는 함수
arr1.mean()

5.5